[profile.dev]
# Non optimized builds can cause time deadline misses on embedded targets.
opt-level = 3
overflow-checks = false

[build]
target = "thumbv6m-none-eabi"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip STM32F031C6Tx"